// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A feature the plugin can offer, as reported by `get_status`.
 */
export type Feature = "notify" | "notificationActions" | "inhibitSleep" | "launcherProgress" | "fileManager" | "globalShortcuts";
