// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Feature } from "./Feature";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * Whether one feature works on this system.
 */
export type FeatureStatus = { feature: Feature, available: boolean, 
/**
 * Why the feature is unavailable; absent when it works.
 */
reason: UnavailableReason | null, 
/**
 * The error text behind the reason, for logs and the Services panel.
 */
detail: string | null, };
