// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether this process owns `org.freedesktop.FileManager1`.
 *
 * This is the return value of `own_file_manager` and `disown_file_manager` and the payload of the
 * `desktop-integration://file-manager-ownership` event, which also reports a name taken away.
 */
export type FileManagerOwnership = { owned: boolean, 
/**
 * Why the name is not owned, when it was lost or could not be taken.
 */
reason: string | null, };
