// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileManagerMethod } from "./FileManagerMethod";
import type { FileManagerTarget } from "./FileManagerTarget";

/**
 * Payload of the `desktop-integration://file-manager` event.
 */
export type FileManagerCall = { method: FileManagerMethod, targets: Array<FileManagerTarget>, 
/**
 * The caller's startup id, for focus-stealing prevention; often empty.
 */
startupId: string, };
