// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `org.freedesktop.FileManager1` method another application called.
 */
export type FileManagerMethod = "show-folders" | "show-items" | "show-item-properties";
