// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One URI from a `FileManager1` call.
 */
export type FileManagerTarget = { 
/**
 * The URI as the caller sent it.
 */
uri: string, 
/**
 * The local path, percent-decoded, when the URI is a `file:` URI for this machine.
 */
path: string | null, };
