// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the `desktop-integration://shortcut-pressed` event.
 */
export type GlobalShortcutPressed = { id: string, };
