// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A global shortcut to register on Windows.
 */
export type GlobalShortcutRequest = { 
/**
 * The caller's id for the shortcut, reported by the `pressed` event.
 */
id: string, 
/**
 * A Tauri-style accelerator such as `Ctrl+Alt+K`.
 */
accelerator: string, };
