// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the launcher or taskbar icon shows.
 */
export type LauncherProgress = { "state": "value", value: number, } | { "state": "indeterminate" } | { "state": "cleared" };
