// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LauncherProgress } from "./LauncherProgress";

/**
 * Progress and count for the app's dock or taskbar entry.
 */
export type LauncherRequest = { progress: LauncherProgress, 
/**
 * A badge count, such as the number of running jobs; zero hides it. Absent leaves it alone.
 * Linux only.
 */
count: number | null, 
/**
 * The `.desktop` file id the dock matches the signal to; defaults to the bundle identifier.
 * Linux only.
 */
desktopId: string | null, 
/**
 * The window whose taskbar button shows the progress. Windows only; defaults to the first
 * window.
 */
windowLabel: string | null, };
