// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the `desktop-integration://notification-action` event.
 */
export type NotificationAction = { id: string, action: string, };
