// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionButton } from "./ActionButton";
import type { Urgency } from "./Urgency";

/**
 * A desktop notification to show or replace.
 */
export type NotifyRequest = { 
/**
 * The caller's id. Sending the same id again replaces the shown notification.
 */
id: string, title: string, body: string | null, 
/**
 * The action id reported through the `notification-action` event when the user clicks the
 * notification itself.
 */
defaultAction: string | null, urgency: Urgency | null, 
/**
 * The application name the shell shows; defaults to the package name.
 */
appName: string | null, 
/**
 * The `.desktop` file id of the app, so the shell can group and style the notification;
 * defaults to the bundle identifier.
 */
desktopId: string | null, 
/**
 * Buttons to show on the notification, in order. At most 3 are shown; extras are dropped.
 * A press is reported through the `notification-action` event with the button's `id`
 * (`default` is reserved for the click on the notification, and an id must differ from
 * `defaultAction` so the two can be told apart). Servers that do not draw
 * buttons (see the `notificationActions` feature) show only the default click.
 */
actions?: Array<ActionButton>, };
