// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureStatus } from "./FeatureStatus";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * What the plugin can do on the running system.
 */
export type PluginStatus = { 
/**
 * True when at least one feature is available.
 */
available: boolean, 
/**
 * Why nothing is available; absent otherwise.
 */
reason: UnavailableReason | null, features: Array<FeatureStatus>, 
/**
 * Whether this process currently owns `org.freedesktop.FileManager1`.
 */
fileManagerOwned: boolean, };
