// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a service command failed, as a value a caller can branch on.
 */
export type ServiceErrorKind = "unsupported-platform" | "unavailable" | "needs-app-id" | "invalid-argument" | "not-found" | "conflict" | "timeout" | "failed";
