// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload emitted on the `shortcut-changed` event, fired when the user rebinds the
 * shortcut through the compositor's own settings UI (e.g. GNOME Settings → Apps →
 * <App> → Global Shortcuts) rather than through this app. Wayland-only — X11 direct
 * grabs have no equivalent out-of-band rebind path, so this never fires there.
 */
export type ShortcutChangedPayload = { sessionId: string, triggerDescription: string, };
