// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload emitted on the `shortcut-activated` event, fired when the shortcut
 * registered via the `register_shortcut` command is pressed. Rust consumers using
 * `DesktopIntegrationExt::register_shortcut` directly get a real closure instead —
 * this event exists so JS-only consumers can use the plugin without writing Rust.
 */
export type ShortcutActivatedPayload = { sessionId: string, };
