// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload emitted on the `shortcut-binding-result` event.
 */
export type ShortcutBindingResult = { success: boolean, error: string | null, };
