// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SleepKind } from "./SleepKind";

/**
 * A request to keep the machine awake.
 */
export type SleepInhibitRequest = { 
/**
 * What the user is told the app is doing, such as "Copying 3 files".
 */
reason: string, 
/**
 * What to inhibit; empty means sleep only.
 */
kinds: Array<SleepKind>, };
