// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The handle of a live sleep inhibitor, to give back to `release_sleep_inhibit`.
 */
export type SleepInhibitHandle = { handle: number, };
