// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to keep the machine from doing.
 */
export type SleepKind = "sleep" | "idle";
