// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a feature is not available.
 */
export type UnavailableReason = "platform-unsupported" | "no-session-bus" | "no-notification-server" | "no-logind" | "needs-app-id" | "no-display-server" | "actions-unsupported";
