// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How urgent a notification is.
 */
export type Urgency = "low" | "normal" | "critical";
