// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One action button on a notification.
 */
export type ActionButton = { 
/**
 * Reported as the event's `action` when the button is pressed. An id that starts with
 * `app.` is instead activated through `org.freedesktop.Application` and never reaches the
 * event.
 */
id: string, 
/**
 * The text on the button.
 */
label: string, };
