// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Colour scheme preference from the desktop portal.
 */
export type ColourScheme = "no-preference" | "prefer-dark" | "prefer-light";
