// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Desktop environment family, used to select widget style maps.
 */
export type DesktopEnvironment = "gnome" | "kde" | "cinnamon" | "mate" | "xfce" | "unknown";
