// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortalFeature } from "./PortalFeature";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * Whether one portal interface works on this session.
 */
export type FeatureStatus = { feature: PortalFeature, available: boolean, 
/**
 * Why the feature is unavailable; absent when it works.
 */
reason: UnavailableReason | null, 
/**
 * The error text behind the reason, for logs and the Services panel.
 */
detail: string | null, 
/**
 * The version of the portal interface, when it was read.
 */
version: number | null, };
