// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to keep the session from doing.
 */
export type InhibitKind = "idle" | "suspend";
