// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InhibitKind } from "./InhibitKind";

/**
 * A request to keep the session from idling or suspending.
 */
export type InhibitRequest = { 
/**
 * What the user is told the app is doing, such as "Copying 3 files".
 */
reason: string, 
/**
 * What to inhibit; empty means both.
 */
kinds: Array<InhibitKind>, };
