// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionButton } from "./ActionButton";
import type { Urgency } from "./Urgency";

/**
 * A desktop notification to show or replace.
 */
export type NotificationRequest = { 
/**
 * The caller's id for this notification. Sending the same id again replaces the shown one;
 * withdrawing takes it off screen.
 */
id: string, title: string, body: string | null, 
/**
 * The action id to report through the `action` event when the user clicks the notification
 * itself. An id that starts with `app.` is instead activated through the
 * `org.freedesktop.Application` interface and never reaches the event.
 */
defaultAction: string | null, urgency: Urgency | null, 
/**
 * Buttons to show on the notification, in order. At most 3 are shown; extras are dropped.
 * A press is reported through the `action` event with the button's `id`. Desktops that do
 * not draw buttons (see the `notificationActions` feature) show only the default click.
 */
actions?: Array<ActionButton>, };
