// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the `xdg-portal://notification-action` event.
 */
export type NotificationAction = { 
/**
 * The id of the notification the user acted on.
 */
id: string, 
/**
 * The action id: the request's `defaultAction` for a click on the notification, or the `id`
 * of the button that was pressed.
 */
action: string, };
