// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A request to open a URI or a local file or folder with the user's chosen application.
 */
export type OpenUriRequest = { 
/**
 * A URI with a scheme. `file:` URIs open a file or, when the target is a folder, show it.
 */
uri: string, 
/**
 * Always ask which application to use.
 */
ask: boolean | null, 
/**
 * Open the file for writing. Applies to `file:` URIs.
 */
writable: boolean | null, };
