// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureStatus } from "./FeatureStatus";
import type { UnavailableReason } from "./UnavailableReason";

/**
 * What the plugin's portal features can do on the running session.
 */
export type PortalStatus = { 
/**
 * True when at least one feature is available.
 */
available: boolean, 
/**
 * Why nothing is available; absent otherwise.
 */
reason: UnavailableReason | null, 
/**
 * Whether this process runs inside a Flatpak or Snap sandbox.
 */
sandboxed: boolean, features: Array<FeatureStatus>, };
