// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceErrorKind } from "./ServiceErrorKind";

/**
 * The error of every notification, inhibit and open-URI command: a `kind` to branch on and a
 * `message` for logs.
 */
export type ServiceError = { kind: ServiceErrorKind, message: string, };
