// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a portal service command failed, as a value a caller can branch on.
 */
export type ServiceErrorKind = "unsupported-platform" | "portal-unavailable" | "not-allowed" | "invalid-argument" | "not-found" | "timeout" | "failed";
