// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentColour } from "./AccentColour";
import type { ColourScheme } from "./ColourScheme";
import type { DesktopEnvironment } from "./DesktopEnvironment";

/**
 * Combined theme information from the desktop portal and environment.
 */
export type ThemeInfo = { colourScheme: ColourScheme, accentColour: AccentColour | null, highContrast: boolean, desktopEnvironment: DesktopEnvironment, };
