// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a feature is not available.
 */
export type UnavailableReason = "platform-unsupported" | "no-portal" | "interface-missing" | "no-response" | "not-sandboxed" | "actions-unsupported";
