// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How urgent a notification is; the portal maps it to the shell's own priority levels.
 */
export type Urgency = "low" | "normal" | "high" | "urgent";
